name: CI-Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build program
        run: ./build.sh
        working-directory: ./cicd

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v4
        with:
          name: latin-checker-binary
          path: usr/bin/latin-checker
          retention-days: 1

  Test:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential tree

      - name: Create usr/bin/ directory for binary
        run: mkdir -p usr/bin
        working-directory: .

      - name: Download binary from artifact
        uses: actions/download-artifact@v4
        with:
          name: latin-checker-binary
          path: usr/bin

      - name: Give permissions to binary
        run: chmod +x latin-checker
        working-directory: ./usr/bin

      - name: Run tests
        run: ./test.sh
        working-directory: ./cicd

  Package:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Create usr/bin directory
        run: mkdir -p usr/bin
        working-directory: .

      - name: Download binary from artifact
        uses: actions/download-artifact@v4
        with:
          name: latin-checker-binary
          path: usr/bin

      - name: Build package
        run: ./package.sh "latin-checker_1.0_amd64.deb"
        working-directory: ./cicd

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: latin-checker-deb-package
          path: latin-checker_1.0_amd64.deb

  Deploy:
    needs: Package
    runs-on: ubuntu-latest

    steps:
      - name: Ensure docker is available
        run: docker --version

      - name: Clone repo
        uses: actions/checkout@v4

      - name: Download deb-package
        uses: actions/download-artifact@v4
        with:
          name: latin-checker-deb-package
          path: ./

      - name: Build docker image
        run: |
          docker build -t ilgringoartur/latin-checker:1.0.0 -f cicd/Dockerfile .
          docker tag ilgringoartur/latin-checker:1.0.0 ilgringoartur/latin-checker:latest

      - name: Run container
        run: |
          echo "3\n1 2 3\n2 3 1\n3 1 2" | docker run -i ilgringoartur/latin-checker:1.0.0

      - name: Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_NAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        run: |
          docker push ilgringoartur/latin-checker:1.0.0
          docker push ilgringoartur/latin-checker:latest
